### ISSUE TITLE
database models

### ISSUE THREAD

**Issue by mahmoudhammad309** [CA-G12/GeekSchool#12]
- [ ] assignments
- [ ] feedback
- [ ] questions
- [ ] assignment_student_teacher
- [ ] schedules

**Comment by Aaya-Elsharief** [comment]
- [ ] students
- [ ] notes
- [ ] tests
- [ ] announcements

**Comment by Bas-Shiekh** [comment]
- [ ] health
- [ ] teachers
- [ ] recommendations

**Comment by moustf** [comment]
- [ ] parent.
- [ ] announcements.
- [ ] classes.
- [ ] test_student.
- [ ] class_student
